extends Node2D

func _ready() -> void:
	var newGrammar = TraceryLoader.createGrammarDictionary("res://resources/Json/TestJson.json")
	print(TraceryLoader.getSentenceFromGrammarDictionary(newGrammar))
	print(TraceryLoader.getSentenceFromGrammarDictionary(newGrammar))
	print(TraceryLoader.getSentenceFromGrammarDictionary(newGrammar))
	print(TraceryLoader.getSentenceFromGrammarDictionary(newGrammar))
	print(TraceryLoader.getSentenceFromGrammarDictionary(newGrammar))
	print(TraceryLoader.getSentenceFromGrammarDictionary(newGrammar))
	print(TraceryLoader.getSentenceFromGrammarDictionary(newGrammar))
	print(TraceryLoader.getSentenceFromGrammarDictionary(newGrammar))
	print(TraceryLoader.getSentenceFromGrammarDictionary(newGrammar))
	print(TraceryLoader.getSentenceFromGrammarDictionary(newGrammar))
	print(TraceryLoader.getSentenceFromGrammarDictionary(newGrammar))
	print(TraceryLoader.getSentenceFromGrammarDictionary(newGrammar))
	print(TraceryLoader.getSentenceFromGrammarDictionary(newGrammar))
	print(TraceryLoader.getSentenceFromGrammarDictionary(newGrammar))
	print(TraceryLoader.getSentenceFromGrammarDictionary(newGrammar))
	print(TraceryLoader.getSentenceFromGrammarDictionary(newGrammar))
